### ISSUE TITLE
Estructura de directorios

### ISSUE THREAD

**Issue by Degryll** [Degryll/ZBE#1]
#### Actualmente tenemos:

ZBE |
        | - bin: Executables generados
        | - build: para compilar en distintos IDE
        | - extlibs: Bibliotecas externas
        | - include: Cabeceras
        | - lib: Bibliotecas generadas
        | - src: Código fuente

####  ¿Dónde colocamos otros recursos como imagenes, videos, texturas, sonidos, etc?

Propongo data, quedando:
  | - data |
  | ------- | - images |
  | ------- | ----------- | - textures
  | ------- | ----------- | - sprites
  | ------- |
  | ------- | - sounds |
  | ------- | ----------- | - Music
  | ------- | ----------- | - efects
  | ------- | 
  etc.

####  ¿Qué estructura tendrá el código?

Por evitar que se convierta en un cajon de sastre hay que discutir una estructura de directorios (y tal vez de bibliotecas) a seguir. Me gustaría iniciar la discusión antes de empezar a pasar código para que no nos suceda como en la estructura anterior en la que acaba apareciendo una carpeta foo con basura "por si aca".

Además de separar en carpetas Archetype, behaviors que es bastante clara, hay que aclarar ciertas dudas:

####  ¿los pintadores van en una carpeta de Drawers o en una especifica de tecnología?

Si hay una carpeta de drawers, es posible que dentro de ella se cree una especifica de tecnología (drawers/SDL, drawers/OGL, etc...) y se repita una estructura similar en los que ejecutan sonidos (sounders?, players?).

Otra alternativa es que dentro de la carpeta OGL esté todo lo relaccionado con esta tecnología, encontrandose dentro pintadores y demas( OGL/drawers, OGL/sounders, SDL/drawers, etc).

O ignorar por completo la tecnología, pero no se si esto es buena idea.

####  Ya que la idea es que el motor sea muy modular (en un muy amplio sentido), ¿tiene sentido un directorio Core con lo básico del sistema?

Estoy pensando en una estructura (tanto para directorios como para bibliotecas) similar a la de OpenCV, donde hay una parte core con los tipos de datos básicos como cv::Mat y luego muchas bibliotecas para procesamiento de imagenes, calibracion de cámaras, detección de objetos, etc.

Actualmente tenemos una carpeta tools donde metemos tanto estructuras de datos (containers) como objetos y operaciones matematicas (vectores, calculo de la normal, etc.) como el systema de errores, o lectura de ficheros de configuración.

Considero que parte de esa funcionalidad es basica (core). Mi propuesta es:

  | - core: Estructuras de datos, systemas para el motor como el de errores o de logs.
  | - math: Todo lo relaccionado con matematicas que será mucho.
  | - tools: leer ficheros de configuración por ejemplo.

######  Problemas:

Core esta pobremente definido, ¿por qué la lectura de ficheros no es core y si una lista de borrado rápido?
Dentro de math posiblemente esté la parte encargada de las físicas en una subcarpeta.
Tools potencialmente se puede convertir en una carpeta foo pero con nombre.

Opiniones.

**Comment by Ludovicio** [comment]
Tarea terminada hace eones. (En escala informática).
Quien quiera saber como quedó la estructura de directorios, que se lo baje. Ya seremos formales con lo siguientes issues.

**Comment by Ludovicio** [comment]
Pues parece que de terminada nada. Se reabre mientras se reorganizan las carpetas del proyecto.
Para que, finalmente, gana la opción "actuadores/tecnologías"

**Comment by Ludovicio** [comment]
Se re-ordenan las carpetas para que sigan el formato "actuadores/tecnologías".
