### ISSUE TITLE
Chapa y pintura

### ISSUE THREAD

**Issue by Ludovicio** [Degryll/ZBE#101]
- Revisar sprites de texto. Se debe porder configurar cosas como, margen, padding, alineación...

- ~~Revisar uso de Boost. Si no se está usando, se debe quitar.~~

- Revisar uso de smart pointers/punteros.

**Comment by Ludovicio** [comment]
Revisar documentación y naming de SysTime. Con la documentación actual es complicado entender que representa cada tiempo.

**Comment by Ludovicio** [comment]
Hay que sacar la carpeta "graphics" de "ZBE/core/tools/graphics" a "ZBE/core/graphics" o "ZBE/graphics"

**Comment by Ludovicio** [comment]
El pintado no pintado no pertenece a la funcionalidad básica: Podrías tener una compilación solo para server que no llevase nada de pintado.
Por ello se deben sacar los sprites de "ZBE/core/entites/avatars" y dejarlos por debajo de "ZBE/entites/avatars"

**Comment by Ludovicio** [comment]
Sobrecargar implementar "operator()" en "Value" para no tener que llamar siempre  a "getValue".

**Comment by Ludovicio** [comment]
_CollisionEventGenerator_ debe desaparecer.
Toda su funcionalidad la cumple _InteractionEventGenerator_

**Comment by Ludovicio** [comment]
Eliminar librerías y versiones de librerías que no se están usando.

**Comment by Ludovicio** [comment]
Tener en cuenta la posibilidad de añadir subespacios de nombres en los ficheros de funciones de utilidad.

Por ejemplo:

OALUtils declara sus funciones dentro de "zbe".
Quizás debiesen declararse dentro de un subespacio "zbe::oal".

**Comment by Ludovicio** [comment]
Crear carpeta de implementaciones dentro de demonios.

**Comment by Ludovicio** [comment]
Mover MainLoop a daemons.

**Comment by Ludovicio** [comment]
Crear ficheros include por categorías. (daemons.h, behaviors.h ... )

**Comment by Ludovicio** [comment]
Crear ficheros de literales por contexto.

**Comment by Ludovicio** [comment]
Revisar uso de WeakAvatarEntityContainer en Actuator.
Si siempre usamos Actuator de la forma:

    Actuator<WeakAvatarEntityContainer<T> >

Quizás WeakAvatarEntityContainer deba incluirse en Actuator para que vuelva a ser:

    Actuator<T>

**Comment by Ludovicio** [comment]
Diccionarios:

Se crearán diccionarios para valores: uint64_t, int64_t, float, double...

El acceso a estos valores no deberá asumir, desde las factorías, que exista ningún espacio de nombres.
Si se desea usar espacios de nombres (buena idea) se deberán incluir completos en los ficheros de configuración.

Se debe modificar las factorias existentes para que sigan esta norma.

Ya disponemos de un diccionario para ids (uint64_t). El que creemos será un template que relacionará un nombre con el tipo que deseemos.
El actual diccionario de ids desaparece y se creará una especialización del template para uint64_t con el nombre del diccionario actual.
El diccionario para uint64_t tiene dos usos:
* valores: nueva funcionalidad.
* Ids: funcionalidad actual.

**Comment by Ludovicio** [comment]
Revisar uso del método insert de RsrcStore.
En lugar de:

    uint64_t id = SysIdGenerator::generate();
    nameRsrcDictionary.insert("nombre",id);
    rsrcStore.insert(id, myInstance);
    
Se debe usar:

    rsrcStore.insert("nombre", myInstance);

**Comment by Degryll** [comment]
Hay clases de prueba que se crean en más de un test (como DummyDaemon) tal vez nos interese tener solo una implementación que los test que quieran las usen.

**Comment by Ludovicio** [comment]
Sacar del core las dependencias de SDL.
De SDLSocket se puede extraer una interfaz.
