### ISSUE TITLE
Resolver test SDLEventDispatcher

### ISSUE THREAD

**Issue by Ludovicio** [Degryll/ZBE#127]
- En windows el test falla por que aparece un evento de ratón (genera 2 evento).
- En widnows habrá que descartar esos eventos espureos y solo tener en cuenta los que crea el test.

**Comment by Degryll** [comment]
Los EventWatchers dicen quien está escuchando eventos, por ahora nuestro watcher de teclado y raton además de ImGui.

Al añadir los watchers se soluciono solo el test (raro).
Solucionado error en test del starter.
