### ISSUE TITLE
Event Dispatcher

### ISSUE THREAD

**Issue by Degryll** [Degryll/ZBE#19]
Crear una clase que recibe la clase abstracta Events y en función de la clase concreta que sea se la pasa a un manejador de eventos. Para implementar esta clase se sigue el patrón visitor.

Actualmente hay un fichero para cada tipo de evento, a partir de ahora se agruparán.

*\* SDLEventDispatcher ahora tiene un nombre no apropiado, habrá que cambiarlo. **

**Comment by Degryll** [comment]
Hecho, falta la llamada a los Handlers correspondientes. Esperando a que estén hechos.

**Comment by Degryll** [comment]
Cambio de nombre, el Event Dispatcher llama a los distintos Event Manager (antes handler) de Collision, time, etc... y son estos manager los que llamaran a los handler (antes guard).

**Comment by Ludovicio** [comment]
Esto sobra...
Esta funcionalidad ya no es necesaria.
