### ISSUE TITLE
Manejadores de eventos

### ISSUE THREAD

**Issue by RubenBatis** [Degryll/ZBE#20]
Crear la clase abstracta eventhandler, de la que heredarán todos los manejadores de eventos. También el manejador de eventos de teclado que recibirá un evento de teclado y llamará a un demonio de teclado que se encargará de responder al evento.
Crear la clase demonio de teclado, un demonio que recibe el estado de una tecla en el run.

Mentirusca todo.
El demonio de teclado no existe. Será un demonio de una clase de demonios que recibirán eventos.

**Comment by Ludovicio** [comment]
Funcionalidad obsoleta. Revisar #43 #44.
