### ISSUE TITLE
Revisión de criterios de inicio y fin de frame.

### ISSUE THREAD

**Issue by Ludovicio** [Degryll/ZBE#23]
Se debe revisar que criterio se está usando para decidir cuando algo ocurre dentro del frame.
Las acciones ocurridas dentro de un frame se están buscando, en general, a partir de un instante inicial y final.
Es necesario establecer un convenio coherente para los siguientes problemas:
- El instante inicial: ¿Está incluido en el frame o pertenece al final del frame anterior?
- El instante final: ¿Está incluido en el frame o pertenece al comienzo del frame siguiente?

**Comment by Degryll** [comment]
Criterio:

Tiempo inicial incluido, tiempo final no. Comparación mayor o igual (>=) que tiempo inicial, estrictamente menor (<) que tiempo final.

**Comment by Ludovicio** [comment]
Correcto.
Ahora sigue siendo necesario revisar que ese es el criterio que se está tomando en el código ya escrito.

**Comment by Degryll** [comment]
Ya te digo yo que no se está siguiendo :laughing:

**Comment by Degryll** [comment]
Cambio de planes, el nuevo criterio (si así lo aprovamos) es que el tiempo inicial no esté incluido (mayor estricto >) y el tiempo final sí. 

Este cambio viene de la manera que tenemos de usarlo.  Ejemplo:

- Supongamos que iniciado el juego, el primer frame dura 16ms, buscaremos eventos que hayan sucedido desde el instante 0 a 16ms (esto ya da una pista de que 0 no está incluido).

- Se encuentra un evento en el instante 5ms. Se resuelve.

- Se vuelve a buscar por eventos, pero ahora desde el instante 5ms hasta los 16. Pero el instante 5ms se ha resuelto en elpaso anterior, así que no está incluido.

**Comment by Ludovicio** [comment]
Lo pasado pasado está.
