### ISSUE TITLE
Ciclo de vida de un evento

### ISSUE THREAD

**Issue by Degryll** [Degryll/ZBE#27]
Los eventos son creados (new) por los generator.  <- Hecho
Cuando el eventStore descarta un evento, por que hay otro evento que sucede antes, hay que eliminar el evento (delete). <- Falta!
Cuando el eventManager trata un evento tiene que eliminarlo también (delete). <- Falta?

Resumen:
Son creados por los generator, y mueren al ser descartados (eventStore) o al cumplir su función (Managers).

**Comment by Degryll** [comment]
Actualmente el event store ya borra (delete) los eventos que descarta, y el TimeEventManager, una vez usado, lo borra también.

Falta confirmación del resto de managers.

**Comment by Ludovicio** [comment]
Los crean los generadores y los mata el EventStore.
SIEMPRE O_O
