### ISSUE TITLE
Crear interfaces template de los adaptadores.

### ISSUE THREAD

**Issue by Ludovicio** [Degryll/ZBE#35]
Crear interfaces template para los adaptadores de las clases pintable, colisionable y colisionador.
Aportarán un único método getter para solicitar la estructura correspondiente (pintable colisionable  colisionador) a partir de la clase de entidad definida en el template.

**Comment by Degryll** [comment]
Hecho, falta terminar los Avatares de collisioner y collisionator para engancharlos correctamente.

**Comment by Ludovicio** [comment]
Se ha creado las estructuras solicitadas.
Falta recuperar el código que se ha deshabilitado como consecuencia de este desarrollo.
