### ISSUE TITLE
Actuadores para eventos de colisión.

### ISSUE THREAD

**Issue by RubenBatis** [Degryll/ZBE#37]
Primera Interfaz Actuadores:
Es un template con un único método Act que recibe un collisioner de tipo movible, morible (el tipo que define el template) o nombres aún mejores, un reactobject del segundo collisioner involucrado y un collisiondata.

Reactobject:
Dos partes:
-La clase padre, reactobject que será la que se pase a los actuadores, que no tienen por que saber el tipo del reactobject al que llaman.
-Un template que recibirá al construirse el tipo del reactobject. Este template será el que contenga la funcionalidad de llamar al react (la segunda interfaz del actuador), pero llamará a uno específico de su tipo.

Segunda Interfaz Actuadores:
Contendrá un método react por cada tipo de reactobject. Serán métodos vacios para ser reescritos desde las instancias de Actuator.

**Comment by Ludovicio** [comment]
Funcionalidad terminada.
