### ISSUE TITLE
Entidades básicas para eventos de colisión.

### ISSUE THREAD

**Issue by Ludovicio** [Degryll/ZBE#38]
Se crearán dos entidades para su posterior uso en el sistema de actuadores de colisión definidas en la tarea #37 : 

-  Mobile: Tendrá coordenadas y velocidad. Se ha de sopesar la posibilidad de crear también la interfaz "Positionable" y que herede de esta.

- Dumping: Tendrá un valor de "Dumping" que representa la capacidad de un objeto para "devolver" los impactos que reciba.

Se debe tener en cuenta, también, la posibilidad de crear ambas entidades como interfaces y crear, por tanto, una implementación básica de estas.

**Comment by Degryll** [comment]
Issue terminado.

Se ha creado interfaces Position, Mobile y Damping (no Dumping) con implementaciones simples SimplePosition, SimpleMobile y SimpleDumping.
