### ISSUE TITLE
Avatar Bounceable y adaptador de Damping a DampingBounceable.

### ISSUE THREAD

**Issue by Ludovicio** [Degryll/ZBE#40]
Se creará:
1 - El nuevo avatar Bounceable que representa a una entidad sobre la que se puede botar con un multiplicador de fuerza concreto.
2 - La implementación SimpleBounceable que contendrá un multiplicador fijo para el bote.
2- Un Adaptor (DampingBounceable) que será capaz de contruir un SimpleBounceable a partir de un Damping.

**Comment by RubenBatis** [comment]
Falta cambiar el nombre de BaseDampingBounceableAdaptor.h a SimpleDampingBounceableAdaptor.h
