### ISSUE TITLE
Extraer los tipos concretos del core

### ISSUE THREAD

**Issue by Degryll** [Degryll/ZBE#42]
La idea es que Bounceable, Dumping, Mobile, etc no deberian estar en core, son implementaciones de juegos concretos (más o menos comunes, pero concretas).

Esto nos obliga a sacar a Reactor, la interfaz de Actuator que implementa todos los act con los Bounceable, Morible, etc...

Para conseguir esto, se nos ha ocurrido que tanto Actuator, ReactObject y ReactObjectCommon, tengan un parametro template R que representa el Reactor.

El Reactor pasa a ser algo que el usuario ha de implementar. Se puede deducir automaticamente de los Actuators creados.
  
  ----------------------------------------------
  
El usuario va a crear un arcanoid y define los siguiens actuators:

- Actuator(bola, bloque) -> modifica la velocidad de la bola en función del tipo de bloque
- Actuator(bola, barra) -> modifica la velocidad de la bola en función del lugar donde se produjo la colisión.
- Actuator(bola, escenario) -> modifica la velocidad de la bola normalmente salvo que choque con la parte de abajo.
  
Dado esto, el Reactor será:

     class ArcanoidReactor {
       virtual void act(bloque) {}
       virtual void act(barra) {}
       virtual void act(escenario) {}
     }

     class MiActuadorDePelotas : public Actuator<Bola,ArcanoidReactor> {
       virtual void act(bloque) {...}
       virtual void act(barra) {...}
       virtual void act(escenario) {...}
       // Puedes crear un unico actuator con todas las funciones, o repartir las funciones en varios
       // incluso varios actuators con las mimas funciones
     }

¿Se me ha ocurrido una buena solución ó nos hemos equivocado alquenolegustaelvicio y Yo?

**Comment by Degryll** [comment]
Ya he hecho la separación.

Reactor será dependiente del juego, por ahora he creado una carpeta zombienoid con el reactor vacio que teniamos antes en core. Esta carpeta puede ser donde creamos el arcanoid, la movamos o la borremos. La he creado a modo de ejemplo (uno malo por que no tiene nada).

También he creado la carpeta archetypes fuera de core donde iran arquetipos de entidad que no pertenecen al core de la libreria.

No cierro el issue por si hay algo más que discutir.

¡¡¡NOSOTROS, si hace mucho que fue 2016, CIERRA ESTE ISSUE!!!

**Comment by Ludovicio** [comment]
Probado y funcional.
