### ISSUE TITLE
Gestor para eventos de entrada.

### ISSUE THREAD

**Issue by Ludovicio** [Degryll/ZBE#43]
Se creará un gestor de eventos de entrada que, por cada evento recibido buscará, usando el id de este, su manejador correspondiente y lo ejecutará.
Deberá ser capaz de almacenar, actualizar y "olvidar" el manejador asociado a cada id de evento de entrada.
Con toda probabilidad el gestor usará un mapa interno para asociar id de cada evento de entrada a su manejador.
Tendrá la responsabilidad de liberar la memoria asociada a los eventos que reciba.

**Comment by RubenBatis** [comment]
Hecho.
