### ISSUE TITLE
Test del generador de eventos de collisión

### ISSUE THREAD

**Issue by Degryll** [Degryll/ZBE#51]
El generador de eventos de colisión coloca los eventos generados en el event Store. 
El event store no exporta una lista, sino que cuando se le indica, ejecuta y borra los eventos que tiene almacenados.
Por lo tanto, no hay un test para probar el generador de eventos de colisión. Este test tiene que probar el generador el event store y posiblemente un Actuador de prueba.

Además, en el test actual, a la hora de crear el DummyCollisionatorEntity y DummyCollisionerEntity, deben de heredar de la entidad Adapted, no de la normal.

PD: El collisionator no debería heredar de collisionerCommon en lugar de Collisioner???

**Comment by Ludovicio** [comment]
Terminao.
