### ISSUE TITLE
EntityAdapted recibe Adaptor en el constructor

### ISSUE THREAD

**Issue by Degryll** [Degryll/ZBE#53]
Actualmente las EntityAdapted reciben solo la entidad en el constructor y tienen una función setAdaptor por que en tiempo de ejecución se puede cambiar el adaptor que usan. 

Deberíamos exigir recibir un adaptor en construcción para que el objeto no este medio construido.

**Comment by Ludovicio** [comment]
Aunque que entity ya no existe, AvatarEnittyAdapted ya tiene esta funcionalidad.
