### ISSUE TITLE
Modificar el eventStore para que tenga un método que devuelva el tiempo de los eventos almacenados (bettertime)

### ISSUE THREAD

**Issue by RubenBatis** [Degryll/ZBE#56]
El bucle de juego será algo parecido a:
    - generadores
    - tiempo de evento mas cercano (este issue)
    - "Comportar" entidades hasta que sucede el primer evento
    - Resolver evento más cercano
    - Y como el champu.

**Comment by Ludovicio** [comment]
Hecho.
