### ISSUE TITLE
Constantes de estado del teclado

### ISSUE THREAD

**Issue by Degryll** [Degryll/ZBE#57]
Deben existir constantes que definan el estado del sistema de entreda, que:

zbe::ZBE_KEYDOWN = 1.0;
zbe::ZBE_KEYUP = 0.0;

o algun equivalente. La idea es que no se necesite saber que es 1 y que es 0.

Ademas se pueden añadir otras constantes para entradas analogicas, por ejemplo un joystick puede tener las constantes:

ZBE_TRIGGERED -> pulsado, a cualquier nivel (simula dispositivo binario, pulsado o no).
ZBE_FULL -> joystick pulsado completamente
ZBE_HARD -> joystick muy pulsado pero no a tope.
ZBE_SOFT -> joystick pulsado levemente (para que el personaje ande y no corra).
etc...

**Comment by Degryll** [comment]
Aprovechar para mover todas las constantes de teclado a un lugar mejor.

**Comment by Ludovicio** [comment]
Hecho.
