### ISSUE TITLE
El tiempo no se redondea ¡CUIDADO!

### ISSUE THREAD

**Issue by Degryll** [Degryll/ZBE#61]
A la hora de calcular el tiempo, no se redondea al alza, si el calculo da un número decimal, nos quedamos solo con la parte entera (17.3 ó 17.8 serán 17).

Esto es devido a que si hay una collisión en el instante 17.8 y se redondea hasta 18, cuando se ejecuten los comportamientos hasta la collision (se comportan esos 18), el objeto a atravesado la collision y eso da problemas.

Esto es facil de resolver si los calculos son positivos, ya que con ignorar la parte decimal está. Típicamente se resuelven con:

t = (distance << PRECISION_DIGITS) / velocity;

CUIDADO por que con números negativos, ese redondeo (debido al complemento a 1) puede redondear -17.3 a -18.

**Comment by Degryll** [comment]
La función roundPrecision funciona correctamente solo con número positivos.

**Comment by Ludovicio** [comment]
Esta problemática ya no se da, debido al cambio a coma flotante en el sistema de colisiones.
