### ISSUE TITLE
Actualizar compilador

### ISSUE THREAD

**Issue by Degryll** [Degryll/ZBE#63]
Hay que actualizar la versión del compilador, por salubridad y por que hay un error en gcc 4.9.1 que nos obliga a usar:
-fno-devirtualize

Recordar eliminarlo de las opciones del compilador.

**Comment by Ludovicio** [comment]
Viejo error resucitado en windows:

Al usar un singleton, si el "getInstance" se llama dentro de código .cpp puede no recibir el mismo objeto que el resto de instancias.

Ej:
    SDLEventDispatcher usa el singleton de SysTimer. Si directamente en la función setState llama al getinstance y lo usa, el timer usado puede (suele) ser distinto del usado por el resto del juego.
    Para evitar este error, no vale con crear una variable (normalmente una referencia) a SysTimer que se inicializa en el constructor, puesto que si el constructor está en el cpp, resulta el mismo efecto.
    Hay que crear el constructor en el .h y asignar ahí la referencia que usará el resto de métodos.

**Comment by Degryll** [comment]
Actualizado a la versión 7.1.0.
Actualizadas las librerias externas a:
googletest: la versión en github del 2017-05-14
SDL2: 2.0.5
SDL2_image: 2.0.1
SDL2_ttf: 2.0.14
