### ISSUE TITLE
Eventos instantaneos.

### ISSUE THREAD

**Issue by Ludovicio** [Degryll/ZBE#68]
Se desea que la resolución de eventos pueda generar nuevos eventos que se han de resolver en ese mismo instante.
Por ejemplo:
Bomba!
Un evento de tiempo genera un area de efecto. En ese mismo instante de tiempo se calculan las colisiones, se encolan los eventos correspondientes y se resuelven.

**Comment by RubenBatis** [comment]
Bucle antiguo:

Recibimos un tiempo de frame
Generamos eventos
le pedimos el tiempo del primer evento al almacen de eventos
SI ocurre dentro de mi tiempo de frame
	reaccionamos al evento
 	ejecutamos los comportamientos hasta el momento del evento
SI NO
 	ejecutamos comportamientos hasta el fin de frame
 	vaciamos el almacen de eventos


Bucle nuevo:

Recibimos un tiempo de frame
Generamos eventos "predecibles"
le pedimos el tiempo del primer evento al almacen de eventos
SI ocurre dentro de mi tiempo de frame
    ejecutamos los comportamientos no de reacción hasta el momento del evento
    reaccionamos al evento <- Pueden generarse eventos instantaneos.
    ejecutamos los comportamientos de reaccion hasta el momento del evento
SI NO
     ejecutamos comportamientos no de reacción hasta el fin de frame
     vaciamos el almacen de eventos

**Comment by RubenBatis** [comment]
Hay que añadir además los eventos generados por comportamientos. Serán generados de la misma forma que los de colisión.
Por ejemplo: un comportamiento que diga que cuando la vida de una entidad llega al 50% estalla.
Se resolverá como una colisión en un espacio ficticio entre un punto que representa la vida actual y un plano (por ejemplo) que representa el 50% de la vida. cualquier cosa que modifique el ritmo al que se pierda vida modificará la velocidad de el punto, o lo cambiará de posición.

**Comment by RubenBatis** [comment]
Depende del #73 y #74

**Comment by Ludovicio** [comment]
Hecho.
