### ISSUE TITLE
Eventos instantaneos en el Event Store.

### ISSUE THREAD

**Issue by Ludovicio** [Degryll/ZBE#76]
Event store tendrá dos listas:

1.  Una en la que almacenará los eventos correspondientes al mejor tiempo. Hay que cambiar el multiset con el que se almacenan actualemente los eventos por un forward_list.
2.  Una en la que todos han sucedido a la vez y hay que gestionarlos.

Tendrá un método para cada lista:
1. (actual) Guarda solo los eventos más recientes en la primera lista.
2. Guarda todos los eventos que recibe en la segunda lista. 

ManageEvents() Resolverá los eventos de las dos listas.

**Comment by RubenBatis** [comment]
Done(r kebab)
