### ISSUE TITLE
Revisión de código.

### ISSUE THREAD

**Issue by Ludovicio** [Degryll/ZBE#77]
Se va a revisar todo el código del proyecto asegurando que sigue las normas de estilo descritas en [el wiki](https://github.com/Degryll/ZBE/wiki/Code-revision)

**Comment by Ludovicio** [comment]
Revisadas carpetas:
ZBE/behavior
ZBETest/behavior

**Comment by Ludovicio** [comment]
Revisadas carpeta:
ZBE/entities

**Comment by Degryll** [comment]
Actualmente BehaviorDaemon y DrawerDaemon son punisherDaemon de Behavior<E> (o Drawer<E>) y L.

Podemos cambiar L para decir que será un lista de E.

**Comment by Ludovicio** [comment]
Revisar estructuras comunes desarrolladas en ZBE_MAIN y trasladarlas a ZBE.
Por ejemplo "Resizable" se ha creado dentro de Zombienoid, pero es suficientemente genérica como para llevarla a ZBE.
Esto alcanza a herramientas como demonios, comportamientos, actuadores, manejadores de eventos, pintadores... Hay que revisarlo todo.

**Comment by Ludovicio** [comment]
Se ha revisado todo el código del core según las reglas de estilo.
