### ISSUE TITLE
Main loop

### ISSUE THREAD

**Issue by RubenBatis** [Degryll/ZBE#78]
El bucle principal ya no se escribe en los main. Para ello se creará MainLoop.

El MainLoop, por constructor y mediante setters recibirá demonios para las distintas fases.

    bool keep = true;
    while(keep){
      //Pre daemon
      window.clear();
      sdlEventDist.run();
      sysTime.update();
      // Inner loop
      while (sysTime.isFrameRemaining()) {
        // Predictable events daemon
        gema.run();
        // Esto tal cual
        sysTime.setEventTime(store.getTime());
        if (sysTime.isPartialFrame()) {
          // commonBehaviorMaster
          commonBehaviorMaster.run();
          store.
          // reactBehaviorMaster
          reactBehaviorMaster.run();
        } else {
          // commonBehaviorMaster
          commonBehaviorMaster.run();
          store.clearStore();
        }
        sysTime.updateInitTime();
      }
      //Post daemon
      drawMaster.run();
      window.present();
      // end
    }

**Comment by Ludovicio** [comment]
Hecho.
