### ISSUE TITLE
Tickets y listas.

### ISSUE THREAD

**Issue by Ludovicio** [Degryll/ZBE#8]
Se requiere el desarrollo de un sistema de contenedores que permita la siguiente funcionalidad:
 Al insertar un elemento en el contenedor, este devolverá una "ticket" que representará al elemento insertado. Con este ticket se podrá realizar ciertas acciones referentes al comportamiento del elemento insertado en dicho contenedor.
 Permitirá:
* Marcar el elemento como eliminado.
* Marcar el elemento como inactivo. (no será devuelto al iterar sobre el contenedor)
* Marcar el elemento como activo. (si será devuelto al iterar sobre el contenedor )

Para ello se desarrollarán las siguientes estructuras:

### Ticket
Servirá como referencia a un elemento de un contenedor y permitirá realizar sobre el las tareas mencionadas (eliminado, activado/desactivado).

### Conjunto iterable con tickets (interfaz)
Al insertar insertar un elemento en el, devolverá un ticket para el manejo de ese elemento.
Cuando itere sobre los elementos almacenados, realizará las tareas correspondientes al ticket asociado a cada elemento. De este modo leerá, ignorará o borrará cada elemento sobre el que itere según esté configurado este.

### Contenedor simple con soporte para tickets (Implementación)
Realizará las tareas descritas en la interfaz, siendo irrelevante el orden en el que estos sean leídos.

**Comment by Degryll** [comment]
He implementado un wrapper para la forward list de la STL que la hace compatible con los Tickets.

Creada la clase TicketedForwardList y TicketedForwardListIterator.
La funcionalidad de la lista es la siguiente (se puede extender de ser necesario):
- begin() y end() para crear el iterador correspondiente.
- push_front(T element) para insertar elementos.

La funcionalidad del iterador es la esperada para un iterador.
