### ISSUE TITLE
Zombienoid

### ISSUE THREAD

**Issue by Ludovicio** [Degryll/ZBE#81]
Usando las herramieantas existentes, se va a desarrollar un juego tipo "Arkanoid" con las siguientes caracteristicas:

(Se marcan con "V" los que finalmente han sido desarrollados y con "X" los que se dejan para más adelante.)

* Elementos:
- [x] - Borde y fondo de mapa.
- [ ] - HUD: vidas, puntos, tiempo. (falta tiempo y nivel, al menos)

* Ladrillos:
- [x] - Ladrillos con varios niveles de vida. (que ya tenemos ladrillos de colores!).
- [ ] - Ladrillos de final de mapa. Cuando los rompes vas a otro nivel. Puede haber uno o varios y cada uno te manda a un nivel fijo.

- [x] - Pelotas.

- [x] - Barra.

* Items: (animados)
- [x] - Vidas... pues vidas.
- [x] - Acelerador.
- [x] - Decelerador.
- [ ] - Alarga barra.
- [ ] - Encoge barra.
- [x] - Engorda pelotas.
- [x] - Encoge pelotas.
- [x] - Multiplicador: Cada bola en tres-> una en la dirección actual y una a cada lado con un angulo dado.
- [x] - Bomba:  Si coges el item la bola/s se convierte en un bomba que explota al cabo de un tiempo rompiendo todo en un area y estuneando la barra si la toca.
           La bola debe mostrar un contador del tiempo que le queda para explotar. 
- [x] - Barra pegajosa.
- [ ] - Pelotas inparables: atraviesan y rompen todo.
- [ ] - Pelotas inutiles: no rompen nada pero si botan.
- [ ] - Pelotas fantasma : atraviesan todo sin romper hasta que se les pasa.
- [x] - Puntos: de varias cantidades. Cuanto más puntos da, más rápido va. (varias cantidades si. Lo otro... pasamos)
- [ ] - Armas para la barra: Aparece un cañón en cada lado

- [ ] - Pantalla entre niveles: Muestra puntos conseguidos por ladrillos/tiempo.

* Carga:
- [ ] - Niveles desde un fichero.

- [ ] - Clasificación a disco.

- [x] - Las pelotas botan con distinto ángulo dependiendo de la posición de la barra en que toquen.

* Trasfondo:
Eres un borracho al que ha mordido un zombie. Hace tiempo que se inventó la cura, pero tienes que llegar a tiempo al hospital.
Has de usar tu fuerza de voluntad para luchar contra la infección en tu cerebro y alcanzar el hospital.
Los ladrillos representan partes de tu cerebro. Si rompes muchos es posible que cuando llegues al hospital ya seas un zombie y montes un pequeña masacre.
Los items son botellas porque el alcohol ralentiza la infección. En los caminos alternativos del mapa podría haber cosas como bares y demás que te añadan vida.

- [ ] - Hay varios posibles objetivos:
* Puntos: rompe lo más que puedas en el tiempo dado. (llegarás como zombie)
* Tiempo: Tarda el menor tiempo posible. (llegaras sin convertir)
* Logra ambas cosas... no se, ya lo pensaremos.

**Comment by Ludovicio** [comment]
Test por realizar:
* Si en un TicketedForwardList el último elemento activo se cambia a un estado no activo, al buscar el siguiente se producía un fallo. Esto se debe a que se intentaba avanzar end. (solucionado)
* En un JointTicketedList, estando en el último elemento de una de las listas y buscar el siguiente, no vale con quedarse en el begin de la siguiente lista; esta lista podría estar vacia y, por ello, quedarte apuntando al end de esa lista intermedia.
  Este end no es comparable con el end del Joint, con lo que no será detectado como final y podría ser dereferenciado, produciendo un fallo. (solucionado)

**Comment by Degryll** [comment]
Hay que comprobar que la llamada a TTF_Init(), para inicializar la libreria SDL_TTF, puede ser llamado multiples veces sin conflicto (al ser llamada una vez se inicializa, las subsiguientes llamadas se obvian).

Ahora solo se llama en SDLTextFontStore, si llamarlo varias veces no tiene efectos no deseados, esta todo correcto. Si por el contrario hay que tenerlo en cuenta y solo ser llamado una vez, habrá que implementar un SDLTTF_starter similar a SDL_Starter.

**Comment by Ludovicio** [comment]
Test por realizar:
* AvatarEntityContainer.

**Comment by Ludovicio** [comment]
Dado que no se dispone de una forma sencilla de dotar de múltiples estados a una entidad, se ha hecho una chapuza con los estados de los ladrillo:
Actualemente el estado de los ladrillos representa las vidas. Se necesita representar también en un estado el tipo de ladrillo (ej. explosivo).
Se ha decidido escoger un numero cualquiera, preferiblemente alto, que representa los estados extraños del ladrillo. Todos los valores por debajo de este, se seguirán interpretando como vidas. Este cambio deberá verse reflejado en adapatadores y comportamientos/actuadores.

Este comportamiento se corregirá más adelante cuando se disponga de valores genéricos asociados a las entidades (tipos Value) que permitirán vincultar tantos estados como se desée.

**Comment by Ludovicio** [comment]
Se finaliza el desarrollo inicial con las tareas marcadas en la descripción original.
