### ISSUE TITLE
Entidades

### ISSUE THREAD

**Issue by Ludovicio** [Degryll/ZBE#9]
Se requiere la creación de la siguientes estructuras:
### Entidad
Representará los distintos elementos del motor con carácter propio, desde personajes de un juego, items, o cualquier otra cosa que vaya a interactuar con el resto de elementos del juego.

Deberá ser capaz de:
* Almacenar un id único para la entidad, que se generará automáticamente para esta en el momento de su creación.
* Manejar tickets ( #8 ) asociados a la entidad. Deberá almacenar una colección numerada de tickets, en la que se podrá insertar, sustituir, solicitar o eliminar los tickets a partir del valor numérico asociado (id).
* Para ello, contendrá la funcionalidad necesaria para añadirse a una lista dada, guardando el ticket.
* Estará al cargo de marcar para eliminación la entidad de todas las listas en las que esté almacenado en el momento de  destruirse.

### Entidad colisionadora
Extenderá la funcionalidad de la entidad básica con las siguientes capacidades:
* Contendrá un conjunto con listas de otras entidades colisionables. Estas podrán ser añadidas, eliminadas o accedidas.
* Contendrá una lista de id's (enteros) que representarán la herramientas encargadas de resolver colisiones (desarrollo futuro). Estos id se deberán poder leer, eliminar y añadir.

Bloqueada por:
#8

**Comment by Degryll** [comment]
Hecho.
